# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUIAuthen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUIAuthen

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  
  target 'SwiftUIAuthenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftUIAuthenUITests' do
    # Pods for testing
  end

end
